### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by ghost** [BeatPlay/BetterAmphetaminPlugin#5]
Having this error while compiling

arm-vita-eabi-gcc -Wl,-q -Wall -O3 -nostartfiles   -c -o main.o main.c
In file included from main.c:36:0:
power.h:15:6: error: conflicting types for 'scePowerSetGpuXbarClockFrequency'
 void scePowerSetGpuXbarClockFrequency(int freq);
      ^
In file included from power.h:1:0,
                 from main.c:36:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/power.h:43:5: note: previous declaration of 'scePowerSetGpuXbarClockFrequency' was here
 int scePowerSetGpuXbarClockFrequency(int freq); // Set Clock Frequency of the Gpu Crossbar
     ^
<builtin>: recipe for target 'main.o' failed
make: **\* [main.o] Error 1

**Comment by dreampiggy** [comment]
Fix it to change `power.h` 15 line:
`void scePowerSetGpuXbarClockFrequency(int freq);`
to
`int scePowerSetGpuXbarClockFrequency(int freq);

**Comment by reszx** [comment]
New errors: arm-vita-eabi-gcc -Wl,-q -Wall -O3 -nostartfiles   -c -o main.o main.c
In file included from main.c:36:0:
power.h:15:6: error: conflicting types for 'scePowerSetGpuXbarClockFrequency'
 void scePowerSetGpuXbarClockFrequency(int freq);
      ^
In file included from power.h:1:0,
                 from main.c:36:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/power.h:43:5: note: previous declaration of 'scePowerSetGpuXbarClockFrequency' was here
 int scePowerSetGpuXbarClockFrequency(int freq); // Set Clock Frequency of the Gpu Crossbar
     ^
main.c: In function 'blit_thread':
main.c:92:2: error: expected ';' before 'scePowerSetBusClockFrequency'
  scePowerSetBusClockFrequency(111)
  ^
main.c:99:2: error: expected ';' before 'scePowerSetBusClockFrequency'
  scePowerSetBusClockFrequency(41)
  ^
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by BeatPlay** [comment]
My bad i forgot 1 ";", just clone again and your golden
