### ISSUE TITLE
Overclocking in config.txt doesnt work

### ISSUE THREAD

**Issue by KawaiiOtakuLord** [BeatPlay/BetterAmphetaminPlugin#8]
Setting the auto_oc=1 
Does nothing and the CPU and GPU have default values when in-game

**Comment by BeatPlay** [comment]
This actually doesnt do anything different than v2... just clone the source and compile it! I changed some things in the code, might work better now

**Comment by Catarax** [comment]
Why no official build if it's called 3.5 on the homepage? Thanks.

**Comment by BeatPlay** [comment]
Still not complete guess i will need atleast 2 months, because i have to do some other more important things

**Comment by Catarax** [comment]
Updated to the 3.5 beta.

default_profile=3 is completely ignored, have to do SELECT+L/R to switch for each games.

**Comment by Catarax** [comment]
Can be closed, working on v3.5 Beta 2

**Comment by BeatPlay** [comment]
Closed!
